apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudnode-config
data:
  DB_HOST: "postgresql-cp.iot-db"
  DB_PORT: "5432"
  DB_NAME: "cp-db"
  DB_SSLMODE: "disable"

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI0NGNlNzg5Yi1rcjEtcmVnaXN0cnkuY29udGFpbmVyLm5obmNsb3VkLmNvbS9jb250YWluZXItcGxhdGZvcm0tcmVnaXN0cnkiOnsidXNlcm5hbWUiOiJYQ0ExT2owRnFBOE9NaGFsT1VoSyIsInBhc3N3b3JkIjoiekdneG83WGxwazVvalk3diIsImF1dGgiOiJXRU5CTVU5cU1FWnhRVGhQVFdoaGJFOVZhRXM2ZWtkbmVHODNXR3h3YXpWdmFsazNkZz09In19fQ==
kind: Secret
metadata:
  name: ncr
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USER: YWRtaW4=  # echo -n 'admin' | base64
  DB_PASSWORD: bWFzdGVy  # echo -n 'master' | base64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcore
  labels:
    app: cloudcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcore
  template:
    metadata:
      labels:
        app: cloudcore
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/node-role
                    operator: NotIn
                    values:
                      - "edge"
      containers:
        - name: cloudcore
          image: 44ce789b-kr1-registry.container.nhncloud.com/container-platform-registry/cloudnode:latest
          ports:
            - containerPort: 50051
          env:
            - name: PROFILE
              value: "prod"
          envFrom:
            - configMapRef:
                name: cloudnode-config
            - secretRef:
                name: db-credentials
      imagePullSecrets:
        - name: ncr
---
apiVersion: v1
kind: Service
metadata:
  name: cloudcore
spec:
  selector:
    app: cloudcore
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
