apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcore
  labels:
    app: cloudcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcore
  template:
    metadata:
      labels:
        app: cloudcore
    spec:
      containers:
        - name: cloudcore
          image: cloudcore:latest
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: cloudcore
spec:
  selector:
    app: cloudcore
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
