apiVersion: v1
kind: ConfigMap
metadata:
  name: edgenode-config
data:
  # Common Configuration
  CLOUD_CORE_URL: "133.186.220.226:31151"
  # Data Source Configuration (mqtt or db)
  DATA_SOURCE: "mqtt"
  # Database Configuration
  DB_HOST: "postgresql-cp.edge-db"
  DB_PORT: "5432"
  DB_NAME: "cp-db"
  DB_SSLMODE: "disable"
  # MQTT Configuration
  MQTT_BROKER: "211.188.58.158:1883"
  MQTT_TOPIC: "iot/data"
  MQTT_CLIENT_ID: "edge-node"

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI0NGNlNzg5Yi1rcjEtcmVnaXN0cnkuY29udGFpbmVyLm5obmNsb3VkLmNvbS9jb250YWluZXItcGxhdGZvcm0tcmVnaXN0cnkiOnsidXNlcm5hbWUiOiJYQ0ExT2owRnFBOE9NaGFsT1VoSyIsInBhc3N3b3JkIjoiekdneG83WGxwazVvalk3diIsImF1dGgiOiJXRU5CTVU5cU1FWnhRVGhQVFdoaGJFOVZhRXM2ZWtkbmVHODNXR3h3YXpWdmFsazNkZz09In19fQ==
kind: Secret
metadata:
  name: ncr
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USER: YWRtaW4=  # echo -n 'admin' | base64
  DB_PASSWORD: bWFzdGVy  # echo -n 'master' | base64

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgenode-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgenode
  labels:
    app: edgenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgenode
  template:
    metadata:
      labels:
        app: edgenode
    spec:
      nodeSelector:
        kubernetes.io/node-role: edge
      containers:
      - name: edgenode
        image: 44ce789b-kr1-registry.container.nhncloud.com/container-platform-registry/edgenode:latest
        imagePullPolicy: Always
        env:
          - name: PROFILE
            value: "prod"
        volumeMounts:
          - name: data-volume
            mountPath: /app/data
        envFrom:
        - configMapRef:
            name: edgenode-config
        - secretRef:
            name: db-credentials
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: edgenode-data-pvc
      imagePullSecrets:
      - name: ncr
